export const queryParam = {
    age:                                   'a',
    investmentPreference:                  'ip',
    grossIncome:                           'gi',
    expenses:                              'ex',
    personalUse:                           'pu',
    retirementBenefitType:                 'rbt',
    retirement401kType:                    'rfkt',
    definedContributionMatchPercent:       'dcmp',
    definedContributionMatchLimit:         'dcml',
    definedContributionExpectedReturn:     'dcer',
    hasStockPurchasePlan:                  'hspp',
    stockPurchaseDiscount:                 'spd',
    stockPurchaseLimit:                    'spl',
    healthSavingsMedicalExpenses:          'hsme',
    healthSavingsHSASupported:             'hshs',
    healthSavingsHSAEmployerContributions: 'hshe',
    savingsDesired:                        'sd',
    savingsAlready:                        'sa',
};