export const queryParam = {
    age: 'a',
    grossIncome: 'gi',
    expenses: 'ex',
    personalUse: 'pu',
    retirementBenefitType: 'rbt',
    definedContributionMatchPercent: 'dcmp',
    definedContributionMatchLimit: 'dcml',
    definedContributionExpectedReturn: 'dcer',
    hasStockPurchasePlan: 'hspp',
    stockPurchaseDiscount: 'spd',
    stockPurchaseLimit: 'spl',
    fsaContributions: 'fc',
    savingsDesired: 'sd',
    savingsAlready: 'sa',
};